# Generated by Django 5.0.4 on 2024-04-13 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Имя банка')),
                ('card_name', models.CharField(max_length=255, verbose_name='Основная карты')),
                ('card_name_second', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительная карта')),
            ],
            options={
                'verbose_name': 'Имя банка',
                'verbose_name_plural': 'Имена банков',
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=255, verbose_name='Тип карты')),
            ],
            options={
                'verbose_name': 'Тип карты',
                'verbose_name_plural': 'Типы карт',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='BankCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=255, verbose_name='Название карты')),
                ('expiry_date', models.DateField(verbose_name='Срок действия до')),
                ('name_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.bank', verbose_name='Название Банка')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID владельца карты')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardtype', verbose_name='Тип карты')),
            ],
            options={
                'verbose_name': 'Карта банка',
                'verbose_name_plural': 'Карты банка',
            },
        ),
        migrations.CreateModel(
            name='CashbackOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент Кэшбэка')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('expiry_date', models.DateField(verbose_name='Срок Действия')),
                ('restrictions', models.TextField(verbose_name='Ограничения')),
                ('name_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.bank', verbose_name='Название Банка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Предложение по кэшбэку',
                'verbose_name_plural': 'Предложения по кэшбэку',
            },
        ),
    ]
