# Generated by Django 5.0.4 on 2024-04-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_bank_cardtype_category_bankcards_cashbackoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='card_name_second',
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255, verbose_name='Основная карты')),
                ('card_name_second', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительная карта')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Имя карты',
                'verbose_name_plural': 'Имена карт',
            },
        ),
    ]
