# Generated by Django 5.0.4 on 2024-04-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_customuser_user_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbackoffer',
            name='name_bank',
            field=models.CharField(choices=[('Jusan', 'Jusan'), ('Simply', 'Simply'), ('картакарта', 'картакарта'), ('Bereke All In', 'Bereke All In'), ('Forte Blue', 'Forte Blue'), ('Halyk Bonus', 'Halyk Bonus'), ('Kaspi Gold', 'Kaspi Gold'), ('автокарта', 'автокарта'), ('RBK', 'RBK'), ('Home Credit Lite', 'Home Credit Lite')], verbose_name='Название Банка'),
        ),
    ]
