# Generated by Django 5.0.4 on 2024-04-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cashbackoffer_name_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbackoffer',
            name='cashback_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент Кэшбэка'),
        ),
        migrations.AlterField(
            model_name='cashbackoffer',
            name='conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='cashbackoffer',
            name='restrictions',
            field=models.TextField(blank=True, null=True, verbose_name='Ограничения'),
        ),
    ]
