# Generated by Django 5.0.4 on 2024-04-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_cashbackoffer_cashback_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbackoffer',
            name='name_bank',
            field=models.CharField(choices=[('Jusan Bank', 'Jusan Bank'), ('Simply', 'Simply'), ('CenterCredit Bank', 'CenterCredit Bank'), ('Bereke Bank', 'Bereke Bank'), ('Forte Bank', 'Forte Bank'), ('Halyk Bank', 'Halyk Bank'), ('Kaspi Bank', 'Kaspi Bank'), ('Eurasian Bank', 'Eurasian Bank'), ('RBK', 'RBK'), ('Home Credit Bank', 'Home Credit Bank')], verbose_name='Название Банка'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_card_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_card_name',
            field=models.ManyToManyField(blank=True, null=True, to='cards.cards', verbose_name='Название карты'),
        ),
    ]
